
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    login TEXT,
    password TEXT,
    balance FLOAT,
    withdrawn FLOAT
);

CREATE TABLE IF NOT EXISTS orders (
    user_id INT,
    number BIGINT,
    status TEXT,
    accrual FLOAT,
    uploaded TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS withdrawals (
    user_id INT,
    number BIGINT,
    amount FLOAT,
    processed TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);